apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: auth:latest
        imagePullPolicy: IfNotPresent
        command: ["bash", "./server.sh"]
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: auth-configmap
        - secretRef:
            name: auth-secret
        env:
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
      restartPolicy: Always
