apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
stringData:
  MONGODB_VIDEOS_URI: "mongodb://admin:password@mongodb:27017/videos?authSource=admin"
  MONGODB_MP3_URI: "mongodb://admin:password@mongodb:27017/mp3?authSource=admin"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_USER: admin
  RABBITMQ_PASS: password