apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    type: local

spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-storage-class
  resources:
    requests:
      storage: 10Gi

