apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  selector:
    app: {{.Values.appName}}
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432
