apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  labels:
    type: local
  annotations:
    description: "Persistent Volume for RabbitMQ"

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rabbitmq-storage-class
  hostPath:
    path: "/mnt/data"
