apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.auth.RABBITMQ_DEFAULT_USER}}
  RABBITMQ_DEFAULT_PASS: {{ .Values.auth.RABBITMQ_DEFAULT_PASS}}
type: Opaque
