apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
type: Opaque
stringData:
  GMAIL_ADDRESS: kariukiantony113@gmail.com
  GMAIL_PASSWORD: zaencxhjmbxqscag
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_USER: admin
  RABBITMQ_PASS: password