apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deploy
  labels:
    app: converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
      - name: converter
        image: converter:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: converter-configmap
        - secretRef:
            name: converter-secret
      restartPolicy: Always
