apiVersion: v1
kind:  PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    type: local
  annotations:
    description: "Persistent Volume for MongoDB"

spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: mongodb-storage-class
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/mongodb"
