apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  labels:
    type: local
  annotations:
    description: "Persistent Volume Claim for mongodb"

spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: mongodb-storage-class
  resources:
    requests:
      storage: 10Gi
