apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.root_username }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.auth.root_password }}
