apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}

spec:
  selector:
    app: {{ .Values.appName }}
  clusterIP: None # Headless service for better DNS
  ports:
  - name:  mongodb
    port: 27017
    targetPort: 27017